//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisianUrban
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Apartment
    {
        public int ApID { get; set; }

        [Display(Name = "Address")]
        [Required(ErrorMessage = "Address is required.")]
        public string ApAddress { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Decription is required.")]
        [StringLength(150,ErrorMessage = "Description cannot be more than 150 characters.")]
        public string ApDescription { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is required.")]
        public double ApPrice { get; set; }

        public System.DateTime ApTimeStamp { get; set; }

        public string ApImage { get; set; }

        public int ApRefDetail { get; set; }
    }
}
