//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisianUrban
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ApDetail
    {
        public int ApDetailID { get; set; }

        [Display(Name = "Pet friendly?")]
        public bool ApPetFriendly { get; set; }

        [Display(Name = "Bathroom #")]
        public short ApBathroomNum { get; set; }

        [Display(Name = "Furnished?")]
        public bool ApFurnished { get; set; }
    }
}
