//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisianUrban.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Apartment
    {
        public int ApID { get; set; }

        [Display(Name = "Address")]
        [Required(ErrorMessage = "Address is required.")]
        public string ApAddress { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Description is required.")]
        public string ApDescription { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is required.")]
        public double ApPrice { get; set; }

        [Display(Name = "Date posted.")]
        public System.DateTime ApTimeStamp { get; set; }

        [Display(Name = "Image")]
        public string ApImage { get; set; }

        public int ApRefDetail { get; set; }
        public Nullable<bool> ApStatus { get; set; }
    }
}
