//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisianUrban.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ApDetail
    {
        public int ApDetailID { get; set; }

        [Display(Name = "Pet Friendly")]
        [Required(ErrorMessage = "This information is required.")]
        public bool ApPetFriendly { get; set; }

        [Display(Name = "number of bathrooms")]
        [Required(ErrorMessage = "number of bathrooms required.")]
        public short ApBathroomNum { get; set; }

        [Display(Name = "Furnished")]
        [Required(ErrorMessage = "This information is required.")]
        public bool ApFurnished { get; set; }
    }
}
