//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisianUrban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApDetail
    {
        public int ApDetailID { get; set; }
        public bool ApPetFriendly { get; set; }
        public short ApBathroomNum { get; set; }
        public bool ApFurnished { get; set; }
    }
}
