//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisianUrban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessID { get; set; }
        public string Description { get; set; }
        public System.DateTime DatePosted { get; set; }
        public int CreatorID { get; set; }
    
        public virtual User User { get; set; }
    }
}
